services:
  php-app:
    build: ./app # Builds the PHP app Docker image from the ./php-app directory
    ports:
      - "9000:80" # Maps port 8080 on the host to port 80 in the container
    depends_on:
      - mysql # Ensures MySQL starts before the PHP app

  mysql:
    image: mysql:8.0 # Uses the official MySQL image
    ports:
      - "9001:3306" # Maps port 3306 on the host to port 3306 in the container
    environment:
      MYSQL_ROOT_PASSWORD: root # Root password for MySQL
      MYSQL_DATABASE: demo_db # Initial database to create
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql # Persists MySQL data in a named volume
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql-data:
